### ISSUE TITLE
adjust prepay contract so that it transfers BTcoins

### ISSUE THREAD

**Issue by sponnet** [BlockTube/blocktube-client.0.2#3]
- Transfer some of your BTcoins to the contract 

https://github.com/BlockTube/blocktube-client.0.2/blob/master/app/contracts/BlockTubePrepaid.sol

**Comment by kingflurkel** [comment]
okay, on it.

**Comment by sponnet** [comment]
BTcoins will be earned while viewing movies - so this is not neccesary at the moment.
